version: '3.8'
services:
  hakk-api:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SUPABASE_URL=http://localhost:54321
      - SUPABASE_KEY=your-local-service-key
    depends_on:
      - supabase-db

  supabase-db:
    image: supabase/postgres:15.1.0
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
