version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy-dev
    ports:
      - "8080:${NGINX_PORT:-8080}"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    env_file:
      - ./.env
    environment:
      - NGINX_PORT=${NGINX_PORT:-8080}
      - NGINX_HEADER_NAME=${NGINX_HEADER_NAME}
      - NGINX_SECURE_KEY=${NGINX_SECURE_KEY}
      - SERVER_PORT=${SERVER_PORT:-3001}
      - CLIENT_PORT=${CLIENT_PORT:-3000}
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile.dev
    container_name: hakk-server-dev
    hostname: hakk-server-dev
    ports:
      - "3001:${SERVER_PORT:-3001}"
      - "9229:9229" # For debugging
    volumes:
      # Mount source for live reloading in development
      - ./packages/server:/app/packages/server
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    env_file:
      - ./.env
    environment:
      - NGINX_HEADER_NAME=${NGINX_HEADER_NAME}
      - NGINX_SECURE_KEY=${NGINX_SECURE_KEY}
      - REDIS_SERVICE_PORT=${REDIS_SERVICE_PORT:-3002}
      - REDIS_SERVICE_HOST=hakk-redis-service-dev
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - redis-service
    # Use development start command with nodemon for auto-restart
    command: pnpm --filter server start:dev

  redis-service:
    build:
      context: .
      dockerfile: packages/redis-service/Dockerfile.dev
    container_name: hakk-redis-service-dev
    hostname: hakk-redis-service-dev
    ports:
      - "3002:${REDIS_SERVICE_PORT:-3002}"
      - "9230:9229" # For debugging
    volumes:
      # Mount source for live reloading in development
      - ./packages/redis-service:/app/packages/redis-service
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=hakk-redis-dev
      - REDIS_PORT=${REDIS_PORT:-6379}
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - redis
    # Use development start command with nodemon for auto-restart
    command: pnpm --filter redis-service start:dev

  redis:
    image: redis:alpine
    container_name: hakk-redis-dev
    hostname: hakk-redis-dev
    ports:
      - "6379:${REDIS_PORT:-6379}"
    volumes:
      - redis-data-dev:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: hakk_app-network-dev

volumes:
  redis-data-dev:
    name: hakk-redis-data-dev