services:
  nginx:
    build:
      context: ./nginx # Updated to point to the nginx directory
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    env_file:
      - ./.env # Reference to root .env file
    environment:
      - NGINX_HEADER_NAME=${NGINX_HEADER_NAME}
      - NGINX_SECURE_KEY=${NGINX_SECURE_KEY}
      - SERVER_PORT=${SERVER_PORT:-3001}
      - CLIENT_PORT=${CLIENT_PORT:-3000}
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge
