services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "8080:${NGINX_PORT:-8080}"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    env_file:
      - ./.env
    environment:
      - NGINX_HEADER_NAME=${NGINX_HEADER_NAME}
      - NGINX_SECURE_KEY=${NGINX_SECURE_KEY}
      - SERVER_PORT=${SERVER_PORT:-3001}
      - CLIENT_PORT=${CLIENT_PORT:-3000}
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server

  server:
    build:
      # context: . # Use the root directory as build context 
      context: ./packages/server
      dockerfile: Dockerfile
      # dockerfile: ./packages/server/Dockerfile # Path to Dockerfile relative to context
    container_name: hakk-server
    ports:
      - "3001:${SERVER_PORT:-3001}"
    volumes:
      - ./packages/server:/app
      - /app/node_modules
    env_file:
      - ./.env
      # - ./packages/server/.env
    environment:
      - NGINX_HEADER_NAME=${NGINX_HEADER_NAME}
      - NGINX_SECURE_KEY=${NGINX_SECURE_KEY}
      - REDIS_SERVICE_PORT=${REDIS_SERVICE_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    networks:
      - app-network
    depends_on:
      - redis-service

  redis-service:
    build:
      context: ./packages/redis-service
      dockerfile: Dockerfile
    container_name: hakk-redis-service
    ports:
      - "3002:${REDIS_SERVICE_PORT:-3002}"
    volumes:
      - ./packages/redis-service:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: hakk-redis
    ports:
      - "6379:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
