services:
  nginx:
    build:
      context: . # ✅ Points to the `nginx/` folder itself
      dockerfile: Dockerfile # Explicitly points to your Dockerfile
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./config:/etc/nginx/conf.d # ✅ `rate-limit.conf` is gone; still needed for `default.conf`
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge
